const USER_ROLES = {
  STUDENT: 'student',
  INSPECTOR: 'inspector',
  ADMIN: 'admin'
};

const INCIDENT_STATUSES = {
  SUBMITTED: 'SUBMITTED',
  UNDER_REVIEW: 'UNDER_REVIEW',
  ACTION_TAKEN: 'ACTION_TAKEN',
  DISMISSED: 'DISMISSED'
};

const INCIDENT_SEVERITIES = {
  LOW: 'Low',
  MEDIUM: 'Medium',
  HIGH: 'High',
  CRITICAL: 'Critical'
};

const MEAL_TYPES = {
  BREAKFAST: 'Breakfast',
  LUNCH: 'Lunch',
  DINNER: 'Dinner'
};

const VALID_STATUS_TRANSITIONS = {
  [INCIDENT_STATUSES.SUBMITTED]: [INCIDENT_STATUSES.UNDER_REVIEW],
  [INCIDENT_STATUSES.UNDER_REVIEW]: [INCIDENT_STATUSES.ACTION_TAKEN, INCIDENT_STATUSES.DISMISSED],
  [INCIDENT_STATUSES.ACTION_TAKEN]: [],
  [INCIDENT_STATUSES.DISMISSED]: []
};

const TERMINAL_STATUSES = [
  INCIDENT_STATUSES.ACTION_TAKEN,
  INCIDENT_STATUSES.DISMISSED
];

module.exports = {
  USER_ROLES,
  INCIDENT_STATUSES,
  INCIDENT_SEVERITIES,
  MEAL_TYPES,
  VALID_STATUS_TRANSITIONS,
  TERMINAL_STATUSES
};
